config/routes.rb
Rails.application.routes.draw do
  root 'questions#index'
  resources :users
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#delete'
  resources :questions do
    resources :answers, only: [:create]
    resources :comments, only: [:create]
    resources :votes, only: [:create]
  end
  resources :answers, only: [] do
    resources :comments, only: [:create]
    resources :votes, only: [:create]
  end
  resources :tags, only: [:index, :show]

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  belongs_to :user
  has_many :comments, :as => :commentable
  has_many :votes, :as => :votable

  validates :content, :user_id, :question_id, presence: true

  def votes_total
    self.votes.sum("value")
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def create
    answer = Answer.new(answer_params)
    question = Question.find_by(id: params[:question_id])
    answer.question = question
    answer.user = current_user
    if answer.save
      flash[:success] = "Your answer has been added!"
    else
      flash[:error] = answer.errors.full_messages
    end
    redirect_to question_path(question)
  end

  private
  def answer_params
    params.require(:answer).permit(:content)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.erb
<div class="answer">
  <div class="answer_voting">
    <div class="votes answer_votes" data-answer-id="<%= answer.id %>">
      <a class="upvote" href="#"></a>
      <div class="votes_total"><%= answer.votes_total %></div>
      <a class="downvote" href="#"></a>
    </div>
   </div>
  <div class="answer_details">
    answered <%= answer.created_at %><br>
    <div class="suggested_answer"><%= answer.content %> - <%= answer.user.username %></div>

    <div class="display_comments answer_comments">
      <%= render answer.comments %>
    </div>
    <%= render partial: 'comments/form', locals: {commentable_type: answer, comment: @comment} %>
  </div>
</div>

app/views/answers/_form.html.erb
<div class="answer_form">
  <%= form_tag question_answers_path(question) do %>
    <div class="content">
      <%= text_area(:answer, :content) %>
    </div>
    <%= submit_tag "Post Your Answer" %>
  <% end %>
</div>